# =================================================================== 
# Spring Boot default configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# =================================================================== 

# =================================================================== 
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================== 

# =================================================================== 
# Logging properties
# =================================================================== 

logging:
  config: classpath:logging/log4j2.yml

# =================================================================== 
# Server properties
# =================================================================== 

server:
  port: 8080
  servlet:
    context-path: /api

# =================================================================== 
# Spring specific properties
# =================================================================== 

spring:

  profiles:
    default: dev

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  
  h2:
    console.enabled: true

springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
